import { RepairRequest } from '@/types/repair';
import { storage } from '@/lib/storage';

export function initializeMockData() {
  const existingData = storage.getAll();
  
  if (existingData.length > 0) {
    return; // ถ้ามีข้อมูลอยู่แล้วไม่ต้องสร้างใหม่
  }

  const mockRequests: RepairRequest[] = [
    {
      id: 'REQ-1704880001',
      cctvId: 'CCTV-BK-001',
      location: 'ถนนสุขุมวิท ซอย 21',
      district: 'วัฒนา',
      problem: 'กล้องไม่ทำงาน',
      description: 'กล้องไม่แสดงภาพบนจอมอนิเตอร์',
      priority: 'ด่วน',
      status: 'กำลังซ่อม',
      reportedBy: 'สมชาย ใจดี',
      contactPhone: '081-234-5678',
      createdAt: new Date(2024, 0, 10).toISOString(),
      updatedAt: new Date(2024, 0, 11).toISOString(),
      technicianName: 'ช่างวิทยา',
    },
    {
      id: 'REQ-1704880002',
      cctvId: 'CCTV-PN-045',
      location: 'ถนนพระราม 4 แยกหัวลำโพง',
      district: 'ปทุมวัน',
      problem: 'ภาพไม่ชัด มีสัญญาณรบกวน',
      description: 'ภาพกล้องเบลอและมีจุดดำปรากฏ',
      priority: 'ปกติ',
      status: 'เสร็จสิ้น',
      reportedBy: 'สมหญิง ศรีสุข',
      contactPhone: '082-345-6789',
      createdAt: new Date(2024, 0, 8).toISOString(),
      updatedAt: new Date(2024, 0, 10).toISOString(),
      completedAt: new Date(2024, 0, 10).toISOString(),
      technicianName: 'ช่างสมบูรณ์',
    },
    {
      id: 'REQ-1704880003',
      cctvId: 'CCTV-BK-102',
      location: 'ถนนเพชรบุรี ตัดใหม่',
      district: 'ราชเทวี',
      problem: 'กล้องหมุนไม่ได้',
      description: 'กล้อง PTZ ไม่สามารถควบคุมการหมุนได้',
      priority: 'ด่วนมาก',
      status: 'รอดำเนินการ',
      reportedBy: 'วิชัย มั่นคง',
      contactPhone: '083-456-7890',
      createdAt: new Date(2024, 0, 12).toISOString(),
      updatedAt: new Date(2024, 0, 12).toISOString(),
    },
    {
      id: 'REQ-1704880004',
      cctvId: 'CCTV-ST-078',
      location: 'ถนนสาทร แยกสีลม',
      district: 'สาทร',
      problem: 'สายไฟขาด',
      description: 'ไฟตกระหว่างการเดินสายใหม่',
      priority: 'ด่วน',
      status: 'รอดำเนินการ',
      reportedBy: 'นภา ชัยวัฒน์',
      contactPhone: '084-567-8901',
      createdAt: new Date(2024, 0, 11).toISOString(),
      updatedAt: new Date(2024, 0, 11).toISOString(),
    },
    {
      id: 'REQ-1704880005',
      cctvId: 'CCTV-DT-023',
      location: 'ถนนราชดำริ ใกล้ BTS ราชดำริ',
      district: 'ดุสิต',
      problem: 'ไฟ IR ไม่ทำงาน',
      description: 'กล้องมองไม่เห็นในเวลากลางคืน',
      priority: 'ปกติ',
      status: 'กำลังซ่อม',
      reportedBy: 'ประเสริฐ รุ่งเรือง',
      contactPhone: '085-678-9012',
      createdAt: new Date(2024, 0, 9).toISOString(),
      updatedAt: new Date(2024, 0, 10).toISOString(),
      technicianName: 'ช่างมานะ',
    },
    {
      id: 'REQ-1704880006',
      cctvId: 'CCTV-LD-156',
      location: 'ถนนลาดพร้าว 71',
      district: 'ลาดพร้าว',
      problem: 'HDD เต็ม',
      description: 'ไม่สามารถบันทึกภาพได้ เนื่องจาก HDD เต็ม',
      priority: 'ปกติ',
      status: 'เสร็จสิ้น',
      reportedBy: 'กิตติ บุญมี',
      contactPhone: '086-789-0123',
      createdAt: new Date(2024, 0, 7).toISOString(),
      updatedAt: new Date(2024, 0, 8).toISOString(),
      completedAt: new Date(2024, 0, 8).toISOString(),
      technicianName: 'ช่างสมบูรณ์',
    },
    {
      id: 'REQ-1704880007',
      cctvId: 'CCTV-BN-089',
      location: 'ถนนบางนา-ตราด กม.3',
      district: 'บางนา',
      problem: 'เครื่องบันทึกเสีย',
      description: 'DVR ไม่บูทเครื่อง มีสัญญาณเสียงบี๊บ',
      priority: 'ด่วนมาก',
      status: 'กำลังซ่อม',
      reportedBy: 'อนุชา พิมพ์ดี',
      contactPhone: '087-890-1234',
      createdAt: new Date(2024, 0, 12).toISOString(),
      updatedAt: new Date(2024, 0, 12).toISOString(),
      technicianName: 'ช่างวิทยา',
    },
    {
      id: 'REQ-1704880008',
      cctvId: 'CCTV-PP-034',
      location: 'ถนนพหลโยธิน ซอย 32',
      district: 'พญาไท',
      problem: 'เลนส์กล้องเบลอ',
      description: 'เลนส์มีรอยขีดข่วนและภาพเบลอ',
      priority: 'ปกติ',
      status: 'รอดำเนินการ',
      reportedBy: 'ศิริพร แสงทอง',
      contactPhone: '088-901-2345',
      createdAt: new Date(2024, 0, 13).toISOString(),
      updatedAt: new Date(2024, 0, 13).toISOString(),
    },
  ];

  mockRequests.forEach(req => storage.save(req));
}
