-- Create nvr_status_history table for NVR status data from Google Sheets
CREATE TABLE IF NOT EXISTS nvr_status_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nvr_id TEXT,
  nvr_name TEXT NOT NULL,
  district TEXT DEFAULT 'Unknown',
  location TEXT DEFAULT 'Unknown',
  onu_ip TEXT DEFAULT '',
  ping_onu BOOLEAN DEFAULT true,
  nvr_ip TEXT NOT NULL,
  ping_nvr BOOLEAN DEFAULT true,
  hdd_status BOOLEAN DEFAULT true,
  normal_view BOOLEAN DEFAULT true,
  check_login BOOLEAN DEFAULT true,
  camera_count INTEGER DEFAULT 0,
  recorded_at TIMESTAMPTZ DEFAULT NOW(),
  source TEXT DEFAULT 'google_sheets'
);

-- Add indexes for querying
CREATE INDEX IF NOT EXISTS idx_nvr_status_history_nvr_name ON nvr_status_history(nvr_name);
CREATE INDEX IF NOT EXISTS idx_nvr_status_history_recorded_at ON nvr_status_history(recorded_at);
CREATE INDEX IF NOT EXISTS idx_nvr_status_history_source ON nvr_status_history(source);

-- Add unique constraint to prevent duplicates
CREATE UNIQUE INDEX IF NOT EXISTS idx_nvr_status_history_unique 
ON nvr_status_history(nvr_name, recorded_at, source) 
WHERE recorded_at IS NOT NULL;
