/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "axqbxpsheochasxosfkl"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF4cWJ4cHNoZW9jaGFzeG9zZmtsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgzNTk4MDAsImV4cCI6MjA4MzkzNTgwMH0.o-PSicV6ojlxI0dupNcILXb-RuRj8K9B_W2yN_sTXZs"