create table if not exists nvr_snapshot_history (
  id bigint generated by default as identity primary key,
  camera_name text,
  nvr_ip text,
  nvr_name text,
  snapshot_status text,
  comment text,
  image_url text,
  recorded_at timestamptz,
  created_at timestamptz default now()
);

-- Add index for querying by nvr_name and date
create index if not exists idx_nvr_snapshot_history_nvr_name on nvr_snapshot_history(nvr_name);
create index if not exists idx_nvr_snapshot_history_recorded_at on nvr_snapshot_history(recorded_at);
